#!/bin/bash

echo I am run when you want to publish a new version of #Skynet.
echo I remotely mov the current directory to the old/ #directory,
echo moving the current directory into new old/ directory.

ssh root@busfactor1.ca -C '
set +e
cd html/bin/skynet
if [[ -e old ]]; then
   mv old .old
   mkdir old
   cp -a * old
   mv .old old/old
else
   mkdir old
   cp -a * old
fi
echo -n . >> version
exit
'
#